package com.example.gestionfarmacia.persistence.enums;

public enum Cargo {

    ADMINISTRADOR_GENERAL,
    GERENTE_FARMACIA,
    SUPERVISOR,
    JEFE_DE_DEPARTAMENTO,
    FARMACEUTICO_TITULAR,
    AUXILIAR_FARMACEUTICO,
    ENCARGADO_DE_ATENCION_AL_CLIENTE,
    AUXILIAR_DE_ALMACEN,
    VENDEDOR
}
